# Generated by Django 5.2.4 on 2025-07-21 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_usersession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
